version: '3.3'

services:
  nestjs:
    build: ./
    container_name: gp_be
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      FE_URL: ${FE_URL}
      BUNGEE_HOST: ${BUNGEE_HOST}
      BUNGEE_PORT: ${BUNGEE_PORT}
      BUNGEE_PASSWORD: ${BUNGEE_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_NAME: ${MYSQL_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MOJANG_API: ${MOJANG_API}
      MCHEAD_API: ${MCHEAD_API}
      EASYDONATE_SHOP_KEY: ${EASYDONATE_SHOP_KEY}
      LIQPAY_PUBLIC_KEY: ${LIQPAY_PUBLIC_KEY}
      LIQPAY_PRIVATE_KEY: ${LIQPAY_PRIVATE_KEY}
      LIQPAY_SERVER_URL: ${LIQPAY_SERVER_URL}
      HOTMC_SECRET_KEY: ${HOTMC_SECRET_KEY}
    ports:
      - "3000:3000"
    networks:
      - nestjs_network

networks:
  nestjs_network:
