version: '3.3'

services:
  nestjs:
    build: ./
    container_name: gp_be
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    networks:
      - nestjs_network

networks:
  nestjs_network:
